version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      # - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    # env_file:
      # - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   - MONGODB_USERNAME=max
    #   - MONGODB_PASSWORD=secret
    # env_file:
      # - ./env/mongo.env
volumes:
  data:

# No necesito network porque docker compose crea una con todos los 
# contenedores  por default.