apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: ignacioalquati/kub-demo-tasks:latest
          # volumeMounts:
          #   - name: data-volume
          #     mountPath: /tasks
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks
      # volumes:
      #   - name: data-volume
      #     hostPath:
      #       path: /data
      #       type: DirectoryOrCreate
